### ISSUE TITLE
Distributed collector-worker check on existing Spot installation

### ISSUE THREAD

**Issue by lighteternal** [spacehellas/incubator-spot#3] opened 2018-04-02 09:52 UTC
This is a preliminary traffic ingestion check for all pipelines (flow,dns,proxy) of the distributed collector-worker modules on an existing Spot v1.0 installation. In a summary, the module has flawless performance on netflow files (both .nfcapd and .csv), order of magnitude quicker compared to standard version's ingestion. DNS and proxy ingestion were tested as well with similar results. The proxy collector-worker had issues with specific unicode characters, that were resolved (see relevant test below).

Tests performed:

**FLOW PIPELINE**
File: nfcapd.201601272015, 367MB, (~400.000 flows)
Collector duration: 1min 8s
Worker duration: 2min 33s
SUCCESS

**FLOW PIPELINE**
File: 2018_01_17_13_30/log_https.csv, 440MB, (~3.500.OOO flows)
Collector duration: 2min 28s
Worker duration: 11min 20s
SUCCESS

**FLOW PIPELINE**
File: nfcapd.201601281530, 84KB (~1.000 flows)
Collector duration:  8s
Worker duration: 6s
SUCCESS

**DNS PIPELINE**
File: dnssyn_v2_00014_20170103205808_spot_00001_20170104025930 , 109MB, ~330000 rows
Collector: 33s
Worker: 21s
SUCCESS

**DNS PIPELINE**
File: dns_test01_00098_20160707045956.pcap, 954M, 11.889.932 rows
Collector: 4min 40s
Worker: 3min 45s
SUCCESS 

**PROXY PIPELINE**
File: Bluecoat_ProxySG_Sample.log, 354MB
Collector: 6s

ERROR on collector: 2018-04-02 12:46:51,635 INFO     SPOT.INGEST.PROXY.PoolWorker-1     Published segment-21 to Kafka cluster. [Topic: TEST1, Partition: 0]
2018-04-02 12:46:51,678 INFO     SPOT.INGEST.PROXY.PoolWorker-1     Published segment-22 to Kafka cluster. [Topic: TEST1, Partition: 0]
2018-04-02 12:46:51,699 ERROR    SPOT.INGEST.PRODUCER               [UnicodeDecodeError] 
2018-04-02 12:46:51,699 ERROR    SPOT.INGEST.PROXY.PoolWorker-1     Failed to publish segment-23 to Kafka cluster.
2018-04-02 12:46:51,699 ERROR    SPOT.INGEST.PROXY.PoolWorker-1     [NameError] global name '_store_segment' is not defined

Explanation:
The collector found unsupported character(s) and stopped, resulting in less rows being published to the worker. After substituting line 205 of collector.py:
.format(segid, _store_segment(segid, items, filename, tmpdir))) 
with:
.format(segid, _store_failed_segment(segid, items, filename, tmpdir)))
the ingestion concludes normally, saving the unsent segments to the local staging area.

Also, the worker had ValueError issues that were fixed with an updated version of spot-ingest/pipelines/proxy/streaming.py along with the execution of: 
python setup.py bdist_egg

After fix:
Collector:19s
Worker: 4m 43s 
SUCCESS

Attached ingest_conf.json for reference:
{
    "dbname" : "spot",
    "hdfs_app_path" : "/user/spot",
    "collector_processes":5,
    "ingestion_interval":1,
    "spark-streaming":{
                "driver_memory":"6g",
                "spark_exec":"1",
                "spark_executor_memory":"4g",
                "spark_executor_cores":"2",
                "spark_batch_size":"15"
    },
    "kafka":{
            "kafka_server":"10.0.3.71",
            "kafka_port":"9092",
            "zookeper_server":"10.0.3.71",
            "zookeper_port":"2181",
	    "max_request_size": 1048576,
            "message_size":900000
        },
    "pipelines":{
        "flow":{
            "type":"flow",
            "collector_path":"/home/spotuser/traffic/flow",
            "local_staging":"/home/spotuser/traffic/flow/local_staging/",
            "supported_files":["nfcapd.",".csv"],
            "process_opt":""
        },
        "dns":{
            "type":"dns",
            "collector_path":"/home/spotuser/traffic/dns",
            "local_staging":"/home/spotuser/traffic/dns/tmp/",
            "supported_files":[".pcap"],
            "pkt_num":"650000",
            "pcap_split_staging":"/home/spotuser/traffic/dns/dns_staging",    
            "process_opt":"-E separator=, -E header=y -E occurrence=f -T fields -e frame.time -e frame.time_epoch -e frame.len -e ip.src -e ip.dst -e dns.resp.name -e dns.resp.type -e dns.resp.class -e dns.flags.rcode -e dns.a 'dns.flags.response == 1'"
        },   
        "proxy":{
            "type":"proxy",
            "collector_path":"/home/spotuser/traffic/proxy",
            "supported_files":[".log"],
            "parser":"bluecoat.py"            
        }     
    }
}

**Comment by ktzoulas** [comment] 2018-04-02 13:05
`[NameError]` is now fixed! Thank you @lighteternal 

When a segment fails to transmit to the Kafka cluster (like in your case where an UnicodeDecodeError occurred) then, Distributed Collector stores the failed segment in CSV format under the local staging area. Following, the user can open and inspect the cause of the failure, and then, using `--skip-conversion` option, it could be reloaded and sent to the Kafka cluster.

**Closed as completed by ktzoulas** 2018-04-02 13:05 UTC
Labels: enhancement
